import Head from "next/head";
import { useRouter } from "next/router";
import { Form } from "../../components/Form";
import { Layout } from "../../components/Layout";
import { Client } from "../../core/Client";



export default function FormRoute(){	
	
	return (
		<div>
      <Head>
        <title>Formulário</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center bg-gradient-to-r from-blue-500 to-purple-500 text-white">
        <Layout title="Cadastro Simples">          
          <Form/>
        </Layout>
      </div>
    </div>
	)
}